platform:
    - x64
    - x86

install:
    - npm install -g esy-bash

build_script:
    - esy-bash ./esy-configure --prefix C:/ocaml-bits
    - esy-bash ./esy-build
    - esy-bash cp /cygdrive/c/ocaml-bits/bin/flexlink.exe /usr/local/bin/flexlink.exe
    - echo print_endline "Hello from OCaml";; > C:/ocaml-bits/test.ml
    - esy-bash /cygdrive/c/ocaml-bits/bin/ocamlopt.exe -o C:/ocaml-bits/test-output C:/ocaml-bits/test.ml
    - C:/ocaml-bits/test-output.exe

test: off
